version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: Task-Management-System
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_management_system
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
   
