version: '3.8'

services:
  mysql:
    image: mysql:8.4
    container_name: task-management-system
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_management_system
    ports:
      - "3306:3306"
   